// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_cu5qomDjN_aCZ3YQCrVno8cgwxbK7s',
    appId: '1:900525516829:web:b70e31eb6f63e1eb92bef4',
    messagingSenderId: '900525516829',
    projectId: 'ajeeb-flutter',
    authDomain: 'ajeeb-flutter.firebaseapp.com',
    storageBucket: 'ajeeb-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOp-f-0HFvlygEk3cQuZy9Emabja_hyTg',
    appId: '1:900525516829:android:ae69a2b62fefe6d492bef4',
    messagingSenderId: '900525516829',
    projectId: 'ajeeb-flutter',
    storageBucket: 'ajeeb-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFTYTZMLBFzHlZ_Her-R6Ot8NzJRMEe_k',
    appId: '1:900525516829:ios:2cc38364cbf2f86a92bef4',
    messagingSenderId: '900525516829',
    projectId: 'ajeeb-flutter',
    storageBucket: 'ajeeb-flutter.appspot.com',
    iosBundleId: 'com.example.ajeebdastan',
  );
}
